### PR TITLE
Convert rqt_runtime_monitor to work in ROS 2 Dashing

### PR DESCRIPTION
**Pull request by pjreed**
This makes changes necessary to convert this into a pure Python ament package.  I've tested it in ROS Dashing and Eloquent.

Distro A, OPSEC #2893

Signed-off-by: P. J. Reed <preed@swri.org>

### CODE REVIEW

**Comment by pjreed** [comment]
@dirk-thomas I forgot about this for a bit, just a ping to let you know this is ready.

**Comment by dirk-thomas** [comment]
@pjreed I am not the listed maintainer for this package.

@ablasdel FYI

**Comment by ablasdel** [comment]
Thanks for putting this together @pjreed, I won't be able to set aside time to review, test and release this until after the Foxy release. At that time if all goes well I'll likely release it into all LTS versions (and the rolling release branch)

**Comment by mikeferguson** [comment]
+1 to this -- I've not really reviewed it - but I've tested it on Foxy on MacOSX and it works for me

**Comment by nfry321** [comment]
I've also not reviewed the code but have tried it on Foxy and Ubuntu 20.04 and it works. Very useful thanks @pjreed!

**Comment by albtam** [comment]
+1

 @ablasdel When would you have a chance to review this MR :) ?

**Pull request merged**
